export const EVENT_BUS_LOGOUT = 'EVENT_BUS_LOGOUT';
export const EVENT_BUS_ADD_NEW_INCOMING_MESSAGE_TO_INBOX_RESPONSE =
  'EVENT_BUS_ADD_NEW_INCOMING_MESSAGE_TO_INBOX_RESPONSE';
export const FETCH_SENT_OFFERS = 'FETCH_SENT_OFFERS';
export const DELETE_CONVERSATION = 'DELETE_CONVERSATION';
