export const EVENT_BUS_LOGOUT = 'EVENT_BUS_LOGOUT';
export const EVENT_BUS_ADD_NEW_INCOMING_MESSAGE_TO_INBOX_RESPONSE =
    'EVENT_BUS_ADD_NEW_INCOMING_MESSAGE_TO_INBOX_RESPONSE';
export const JOIN_TO_CHAT_ROOM =
    'JOIN_TO_CHAT_ROOM';
export const SEND_MESSAGE =
    'SEND_MESSAGE';
export const FETCH_SENT_OFFERS = 'FETCH_SENT_OFFERS';