interface IProps {
  title?: string
}

export default function Head({ title }: IProps) {
  return (
    <>
      <title>{title ? title : 'QouHR'}</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
