name: cqed-frontend

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'  # Enable caching for Yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build projects
        run: yarn build
        env:
          NEXT_PUBLIC_API_HOST: ${{ secrets.NEXT_PUBLIC_API_HOST }}

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PROD_PVT_KEY }}
          known_hosts: ${{ secrets.PROD_HOST }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.PROD_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz .next public yarn.lock root@${{ secrets.PROD_HOST }}:/root/apps/cqed-frontend
      - name: SSH into server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          key: ${{ secrets.PROD_PVT_KEY }}
          username: root
          script: |
            echo "Initializing nvm..."
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            echo "Checking Node.js version..."
            node -v
            cd /root/apps/cqed-frontend
            yarn install --production
            pm2 delete cqed-frontend
            export NEXT_PUBLIC_API_HOST=${{ secrets.NEXT_PUBLIC_API_HOST }}
            pm2 start yarn --name "cqed-frontend" -- start
